### ISSUE TITLE
Read only solution of documents?

### ISSUE THREAD

**Issue by cmroanirgo** [nextcloud/documents#6]
As of Nextcloud 12, this project is apparently dead, with no way to enable it from within the next cloud UI.

The recommendation is to "Please, please move to an actively developed app like for example Collabora Online, Onlyoffice or Ownpad."
Unfortunately, every single one of these systems involve an incredible amount of bloat, when sometimes this is not required!

What is available for a simple plugin that can *read* documents in the same way that the PDF viewer can? That is, where is a simple odt/docx viewer?

Unfortunately, by removing support for this plugin, that owncloud/nextcloud becomes increasingly unattractive to me (and is the *prime* reason I went with this architecture). Any help appreciated!

**Comment by cmroanirgo** [comment]
Googling for alternatives revealed this project which seems very active, and seems more in tune with an apache/php server configuration (such that nextcloud needs):

https://github.com/PHPOffice/PHPWord

Any pointers on integrating this with nextcloud?

**Comment by blizzz** [comment]
> As of Nextcloud 12, this project is apparently dead, with no way to enable it from within the next cloud UI.

Why, it's on the app store and compatible with 12.


For all the rest, please bring the topic to the [forums](https://help.nextcloud.com/), because this is neither the right place nor will you find any audience here. Therefore, I also close the issue.
